Sun 05 May 2019 02:45:04 AM MDT

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,36 +1,36 @@
 k() {
-  if [ $TMUX ]; then
-    clear
-    tmux clear-history
-  elif [ $ITERM_SESSION_ID ]; then
-    printf '\e]50;ClearScrollback\a'
-  else
-    tput reset
-  fi
+    if [ $TMUX ]; then
+	clear
+	tmux clear-history
+    elif [ $ITERM_SESSION_ID ]; then
+	printf '\e]50;ClearScrollback\a'
+    else
+	tput reset
+    fi
 }
 
 work() {
-  if [ $1 ] || [ $ACTIVE_PROJ ]; then
-    local proj_dir=$HOME/projects
-    if [ $1 ]; then
-      local targ=$1
+    if [ $1 ] || [ $ACTIVE_PROJ ]; then
+	local proj_dir=$HOME/projects
+	if [ $1 ]; then
+	    local targ=$1
+	else
+	    local targ=$ACTIVE_PROJ
+	fi
+	if [ -d $proj_dir/$targ ]; then
+	    cd $proj_dir/$targ
+	    k
+	    if git rev-parse --is-inside-work-tree &> /dev/null; then
+		git status
+	    fi
+	else
+	    echo "could not find project $targ in $proj_dir"
+	    return 2
+	fi
     else
-      local targ=$ACTIVE_PROJ
+	echo "ACTIVE_PROJ not defined"
+	return 1
     fi
-    if [ -d $proj_dir/$targ ]; then
-      cd $proj_dir/$targ
-      k
-      if git rev-parse --is-inside-work-tree &> /dev/null; then
-        git status
-      fi
-    else
-      echo "could not find project $targ in $proj_dir"
-      return 2
-    fi
-  else
-    echo "ACTIVE_PROJ not defined"
-    return 1
-  fi
 }
 
 fd(){
@@ -40,83 +40,30 @@ fd(){
     $EDITOR $file
 }
 
-# Fuzzy search shell command history
-fh() {
-  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
-}
-
-# Fuzzy open files
-#   - CTRL-O to open with `xdg-open` command,
-#   - CTRL-E or Enter to open with the $EDITOR
-fo() {
-  local out candidates files key prog
-  prog="${EDITOR:-vim}"
-  candidates="$(ls -a | fzf)"
-  out=($(fzf --query="$1" --multi --exit-0 --expect=ctrl-o,ctrl-e <<< ${candidates}))
-  key=$(head -1 <<< "$out")
-  if [ "$key" = ctrl-o ] || [ "$key" = ctrl-e ]; then
-    files="$(tail +2 <<< "$out")"
-    case "$key" in
-    ctrl-o)
-	prog=ranger
-	# xdg-open can only open one file at a time
-	files="$(head -1 <<< "$files")";;
-    ctrl-e)
-	files="$out"
-	key="";;
-    esac
-  fi
-  [ -n "$files" ] && echo "$files" | xargs -d '\n' "$prog"
-}
-
-# Fuzzy cd
-fc() {
-    local dir
-    dir=$(ls -a | fzf +m)
-    cd "$dir"
-}
-
 # Fuzzy SSH
 fssh() {
-  local user_prefix
-  if [ -n "$1" ]; then
-    user_prefix="${1}@"
-  fi
-  ssh "$user_prefix$(grep '^host\b' $HOME/.ssh/config | awk '{print $2}' | fzf)"
+    local user_prefix
+    if [ -n "$1" ]; then
+	user_prefix="${1}@"
+    fi
+    ssh "$user_prefix$(grep '^host\b' $HOME/.ssh/config | awk '{print $2}' | fzf)"
 }
 
 # Fuzzy Tmux attach
 ft() {
-  session="$(tmux ls -F '#{session_name}' | fzf)"
-  if [[ -n "$session" ]]; then
-    tmux a -t "$session"
-  else
-    return 1
-  fi
+    session="$(tmux ls -F '#{session_name}' | fzf)"
+    if [[ -n "$session" ]]; then
+	tmux a -t "$session"
+    else
+	return 1
+    fi
 }
 
-# Edit common config files
-vc() {
-  if [ -z $CONFIG_BOOKMARKS ]; then
-    echo '$CONFIG_BOOKMARKS not defined'
-    return 2
-  fi
-  echo $CONFIG_BOOKMARKS | fzf --query="$1" | sed "s|~|$HOME|" | xargs -r $EDITOR
-}
-
-# Edit common scripts
-vs() {
-  if [ -z $BIN_BOOKMARKS ]; then
-    echo '$BIN_BOOKMARKS not defined'
-    return 2
-  fi
-  find -H $BIN_BOOKMARKS -type f -not -path '*/.git/*' | fzf --query="$1" | sed "s|~|$HOME|" | xargs -r $EDITOR
-}
 ranger() {
     if [ -z "$RANGER_LEVEL" ]; then
-        /usr/bin/ranger "$@"
+	/usr/bin/ranger "$@"
     else
-        exit
+	exit
     fi
 }
 
@@ -130,4 +77,89 @@ ranger() {
 #                 rm $NNN_TMPFILE
 #         fi
 # }
+
+# ------------FZF Keybindings
+if [[ $- == *i* ]]; then
+
+# CTRL-T - Paste the selected file path(s) into the command line
+    __fsel() {
+	local cmd="${FZF_CTRL_T_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
+    -o -type f -print \
+    -o -type d -print \
+    -o -type l -print 2> /dev/null | cut -b3-"}"
+	setopt localoptions pipefail 2> /dev/null
+	eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_CTRL_T_OPTS" $(__fzfcmd) -m "$@" | while read item; do
+	    echo -n "${(q)item} "
+	done
+	local ret=$?
+	echo
+	return $ret
+    }
+
+    __fzf_use_tmux__() {
+	[ -n "$TMUX_PANE" ] && [ "${FZF_TMUX:-0}" != 0 ] && [ ${LINES:-40} -gt 15 ]
+    }
+
+    __fzfcmd() {
+	__fzf_use_tmux__ &&
+	echo "fzf-tmux -d${FZF_TMUX_HEIGHT:-40%}" || echo "fzf"
+    }
+
+    fzf-file-widget() {
+	LBUFFER="${LBUFFER}$(__fsel)"
+	local ret=$?
+	zle reset-prompt
+	return $ret
+    }
+    zle     -N   fzf-file-widget
+    bindkey '^T' fzf-file-widget
+
+# Ensure precmds are run after cd
+    fzf-redraw-prompt() {
+	local precmd
+	for precmd in $precmd_functions; do
+	    $precmd
+	done
+	zle reset-prompt
+    }
+    zle -N fzf-redraw-prompt
+
+# CTRL-O - cd into the selected directory
+    fzf-cd-widget() {
+	local cmd="${FZF_ALT_C_COMMAND:-"command find -L . -mindepth 1 -maxdepth 2 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
+    -o -type d -print 2> /dev/null | cut -b3-"}"
+	setopt localoptions pipefail 2> /dev/null
+	local dir="$(eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_ALT_C_OPTS" $(__fzfcmd) +m)"
+	if [[ -z "$dir" ]]; then
+	    zle redisplay
+	    return 0
+	fi
+	cd "$dir"
+	local ret=$?
+	zle fzf-redraw-prompt
+	return $ret
+    }
+    zle     -N    fzf-cd-widget
+    bindkey '^O' fzf-cd-widget
+
+# CTRL-R - Paste the selected command from history into the command line
+    fzf-history-widget() {
+	local selected num
+	setopt localoptions noglobsubst noposixbuiltins pipefail 2> /dev/null
+	selected=( $(fc -rl 1 |
+		FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )
+	local ret=$?
+	if [ -n "$selected" ]; then
+	    num=$selected[1]
+	    if [ -n "$num" ]; then
+		zle vi-fetch-history -n $num
+	    fi
+	fi
+	zle reset-prompt
+	return $ret
+    }
+    zle     -N   fzf-history-widget
+# bindkey '^i' fzf-history-widget
+
+fi
 # vim:ft=sh
