lots for formatting changes to cabl

diff --git a/dmenu/cabl b/dmenu/cabl
--- a/dmenu/cabl
+++ b/dmenu/cabl
@@ -88,38 +88,47 @@ cd "$(readlink /proc/"${PID}"/cwd)" || exit
 
 # FILE
 prim=$(echo "${prim}" | sed 's/file://g') # Remove file url
-[ -f "${prim}" ] && isfile "${prim}"
+[ -f "${prim}" ] && isfile "${prim}" && exit 1
+
+browse() { exec "${BROWSER}" "${prim}" ; }
+email() { xdg-email "${prim}" && exit; } 
+vimplug() { exec "${BROWSER}" "https://github.com/$(echo "${prim}" | cut -d\' -f2)"; }
+errormsg() { exec "${TERMINAL}" -e "${EDITOR:-vi}" "$(echo "${prim}" | cut -d: -f1)" "+$(echo "${prim}" | cut -d: -f2)" ; }
+date() { 
+	exec "${BROWSER}" "https://calendar.google.com/calendar/r/day/$(echo "${prim}" |
+		awk -F '[- ]' '{$1=$1}1 {printf "%s/%s/%s", $1, $2, $3}' | tr -d '<')"
+	}
 
 # DIRECTORY
-[ -d "$prim" ] && cd "$prim" && exec "$TERMINAL"
-# URL
-echo "${prim}" | grep "^\s*https\?.*\.[A-Za-z]\+.*" > /dev/null && exec "${BROWSER}" "${prim}"
-# EMAIL
-echo "${prim}" | grep "[A-Za-z0-9._%+-]\+@[A-Za-z0-9.-]\+\.[A-Za-z]\{2,6\}\$" > /dev/null && xdg-email "${prim}" && exit
-# VIM PLUGIN
-echo "${prim}" | grep ".*Plug.*'.*/.*'.*" > /dev/null && exec "${BROWSER}" "https://github.com/$(echo "${prim}" | cut -d\' -f2)"
-# ERROR MESSAGE
-echo "${prim}" | cut -d: -f1 | xargs -r test -f &&
-	echo "${prim}" | grep -E '^[A-Za-z/\.-]+:[0-9]+' > /dev/null &&
-	exec "${TERMINAL}" -e "${EDITOR:-vi}" "$(echo "${prim}" | cut -d: -f1)" "+$(echo "${prim}" | cut -d: -f2)" 
+[ -d "$prim" ] && isdir "${prim}" && exit 1
 
-# DATE https://calendar.google.com/calendar/r/day/
-echo "${prim}" | grep '\s*<\?[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [a-zA-Z]\{3\} \?\([0-9]\{2\}:[0-9]\{2\}\)\?>\?\s*' > /dev/null &&
-	exec "${BROWSER}" "https://calendar.google.com/calendar/r/day/$(echo "${prim}" | 
-	awk -F '[- ]' '{$1=$1}1 {printf "%s/%s/%s", $1, $2, $3}' | tr -d '<')"
-
-
+# ONLY ONE LINE
+if [ "$(echo "${prim}" | wc -l )" -eq 1 ] ; then
+	# URL
+	echo "${prim}" | grep "^\s*https\?.*\.[A-Za-z]\+.*" > /dev/null && browse
+	# EMAIL
+	echo "${prim}" | grep "[A-Za-z0-9._%+-]\+@[A-Za-z0-9.-]\+\.[A-Za-z]\{2,6\}\$" > /dev/null && email
+	# VIM PLUGIN
+	echo "${prim}" | grep ".*Plug.*'.*/.*'.*" > /dev/null && vimplug
+	# ERROR MESSAGE
+	echo "${prim}" | cut -d: -f1 | xargs -r test -f &&
+		echo "${prim}" | grep -E '^[A-Za-z/\.-]+:[0-9]+' > /dev/null && errormsg
+			# DATE https://calendar.google.com/calendar/r/day/
+			echo "${prim}" | grep '\s*<\?[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [a-zA-Z]\{3\} \?\([0-9]\{2\}:[0-9]\{2\}\)\?>\?\s*' > /dev/null && date
+fi
 
 # BEGIN OPTIONS
-options=''
+OPTIONS="
+search
+qrcode
+nmaps
+read"
 
-search() { "${BROWSER}" "https://duckduckgo.com/?q=$*"; }                && options="${options}\nsearch"
-	qrcode() { qrencode "$*" -s 10 -o /tmp/qr.png && "$OPENER" /tmp/qr.png; } && options="${options}\nqrcode"
-		maps() { "${BROWSER}" "https://maps.google.com/?q=$*"; }                 && options="${options}\nmaps"
-
-# MAYBE A URL
-echo "${prim}" | grep "^.*\.[A-Za-z]\+.*" > /dev/null &&
-	dhandler() { dmenuhandler "$@"; }               && options="${options}\ndhandler"
+search() { "${BROWSER}" "https://duckduckgo.com/?q=$*"; }
+qrcode() { qrencode "$*" -s 10 -o /tmp/qr.png && "$OPENER" /tmp/qr.png; }
+maps() { "${BROWSER}" "https://maps.google.com/?q=$*"; }
+dhandler() { dmenuhandler "$@"; }
+manual() { man -Tpdf "${prim}" | ${READER} -; }
 
 # READ ALOUD
 read() {
@@ -127,18 +136,21 @@ read() {
 	# aplay /tmp/test.wav -D 'pulse'
 	aplay /tmp/test.wav
 	rm /tmp/test.wav
-} && options="${options}\nread"
+}
+
+
+# MAYBE A URL
+echo "${prim}" | grep "^.*\.[A-Za-z]\+.*" > /dev/null && OPTIONS="${OPTIONS}\ndhandler"
 
 # check if single word
 if [ "$(echo "${prim}" | wc -w)" -eq 1 ]; then
 	# if manpage exists
-	man -w "${prim}" > /dev/null && 
-		manual() { man -Tpdf "${prim}" | ${READER} -; } && options="${options}\nmanual"
+	man -w "${prim}" > /dev/null && OPTIONS="${OPTIONS}\nmanual"
 fi
 
 prompt="Plumb \"$(echo "${prim}" | awk ' NR==1' | cut -c -18)\" to?"
 
-func="$(printf "$options" | awk 'NR>1' | ${LAUNCER} -p "${prompt}" -i -l 15)"
+func="$(printf "$OPTIONS" | awk 'NR>1' | ${LAUNCER} -p "${prompt}" -i -l 15)"
 
 [ -z "${func}" ] || "${func}" "${prim}"
 #vim:ft=sh
