use catt instead of castnow

diff --git a/tools/cast b/tools/cast
--- a/tools/cast
+++ b/tools/cast
@@ -2,38 +2,46 @@
 # uses castthis for different formats
 [ -z "$1" ] && { exit; }
 
-# TODO: add subtitile support <07-03-20 Gavin Jaeger-Freeborn>
+# TODO: add subtitile support
 
 pkill node
 # pgrep will only find *node* and wont find *castnow*
 # ps aux |  castnow | grep -v grep && killall node
 
+# This has moved from castnow to catt
+# https://github.com/skorokithakis/catt
+
+castnow_yt() {
+	tmpdir=$(mktemp -d)
+	file_to_cast=${tmpdir}/cast
+	program_=$(command -v castnow)
+	if [ "${program_}" = "" ]; then
+		notify-send "castnow can't be found..."
+		exit 1
+	fi
+
+	# kill any running instance of castnow
+	pkill -f "${program_}"
+	# setsid castnow ./"$1" --quiet >/dev/null 2>&1 &
+	youtube-dl -qo - "$1" > "${file_to_cast}" &
+	ytdl_pid=$!
+
+	tail -F "${file_to_cast}" | ${program_} -
+	# cleanup remaining background process and file on disk
+	kill ${ytdl_pid}
+	rm -rf "${tmpdir}"
+}
+
 case "$1" in
-	*mkv | *avi)
-		setsid castnow ./"$1" --quiet --tomp4 >/dev/null 2>&1 &
-		;;
+	# *mkv | *avi)
+	# 	setsid catt cast "$1" >/dev/null 2>&1 &
+	# 	;;
 	*youtube.com* | *youtu.be*) #limit the video quality
-		tmpdir=$(mktemp -d)
-		file_to_cast=${tmpdir}/cast
-		program_=$(command -v castnow)
-		if [ "${program_}" = "" ]; then
-			notify-send "castnow can't be found..."
-			exit 1
-		fi
-
-		# kill any running instance of castnow
-		pkill -f "${program_}"
-		# setsid castnow ./"$1" --quiet >/dev/null 2>&1 &
-		youtube-dl -qo - "$1" > "${file_to_cast}" &
-		ytdl_pid=$!
-
-		tail -F "${file_to_cast}" | ${program_} -
-		# cleanup remaining background process and file on disk
-		kill ${ytdl_pid}
-		rm -rf "${tmpdir}"
+		# castnow_yt $1
+		setsid catt cast "$1" &
 		;;
 	*)
-		castnow ./"$1" --quiet >/dev/null 2>&1 &
+		setsid catt cast ./"$1" >/dev/null 2>&1 &
 		;;
 esac
 notify-send " casting video"
